GET http://localhost:8000

###
GET http://localhost:8000/users

###
GET http://localhost:8000/users/db3ada2d-32ee-4859-bd4c-1b6f90a9b7d4

###

PUT http://localhost:8000/users/db3ada2d-32ee-4859-bd4c-1b6f90a9b7d4/click

###
DELETE http://localhost:8000/users/destroy

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Toto",
    "team": "8e5d9458-d0a0-4d1f-8fb1-292f89327003"
}