GET http://localhost:8000

###
GET http://localhost:8000/users

###
GET http://localhost:8000/users/7e2962ef-c987-44ee-8784-8a852dff038


###
GET http://localhost:8000/users/destroy

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Toto",
    "team": "36b9a0ba-e220-43b7-980a-b9b839a6f9e0",
    "TeamUuid": "36b9a0ba-e220-43b7-980a-b9b839a6f9e0"
}