GET http://localhost:8000

###
GET http://localhost:8000/users

###
GET http://localhost:8000/users/c7786bcd-6288-47b9-8663-2aa7d2d8ce52

###

PUT http://localhost:8000/users/c7786bcd-6288-47b9-8663-2aa7d2d8ce52/click

###
DELETE http://localhost:8000/users/destroy

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "pseudo": "Toto",
    "team": "52c2351d-1b66-45cd-8503-536dd0f81a04"
}